### ISSUE TITLE
How to access the application dashboard?

### ISSUE THREAD

**Issue by rodolfobandeira** [mingfang/docker-predictionio#11]
Sorry for the stupid question.. but after I ran the last step "The Dashboard is available on port 9000", how can I access the dashboard? My desktop is not being able to reach the docker's ip. Is it a normal http application? From my desktop: http://172.17.0.22:9000?

From my docker I can ping my desktop ip but from my desktop I can't ping my docker.

```
root@406da2ceba04:/# ifconfig | grep 'inet addr'
          inet addr:172.17.0.22  Bcast:0.0.0.0  Mask:255.255.0.0
          inet addr:127.0.0.1  Mask:255.0.0.0
root@406da2ceba04:/#
```

**Comment by mingfang** [comment]
Use your desktops IP and not the docker IP.

**Comment by rodolfobandeira** [comment]
Tried everything. Maybe some firewall rules on my desk or vagrant?

- Firefox can't establish a connection to the server at localhost:9000.
- Firefox can't establish a connection to the server at 127.0.0.1:9000.
- Firefox can't establish a connection to the server at localhost:9000.
- Firefox can't establish a connection to the server at 192.168.0.138:9000.

This is my listen ports from my Docker:
```
root@406da2ceba04:/# lsof -i | grep LISTEN
java     22 root   89u  IPv6  25992      0t0  TCP *:9300 (LISTEN)
java     22 root  145u  IPv6  23202      0t0  TCP *:9200 (LISTEN)
java     23 root   66u  IPv6  27129      0t0  TCP localhost:7070 (LISTEN)
java     24 root  121u  IPv6  25430      0t0  TCP *:2181 (LISTEN)
java     24 root  126u  IPv6  22342      0t0  TCP 406da2ceba04:50495 (LISTEN)
java     24 root  170u  IPv6  26635      0t0  TCP 406da2ceba04:35849 (LISTEN)
java     24 root  207u  IPv6  23159      0t0  TCP *:59297 (LISTEN)
java     24 root  211u  IPv6  26649      0t0  TCP *:60010 (LISTEN)
java     30 root   16u  IPv6  26058      0t0  TCP *:9000 (LISTEN)
root@406da2ceba04:/#
```

**Comment by mingfang** [comment]
on your host(desktop), can you send the out of ```docker ps```

**Comment by rodolfobandeira** [comment]
Hi @mingfang 

```
docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                            NAMES
c32e6baed4c1        predictionio:latest   "/bin/bash"         5 minutes ago       Up 5 minutes        0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   adoring_babbage
```

I installed Lynx on prediction's shell and it runs perfect when I try:
```
lynx http://localhost:9000
```

The problem is the talking between my host and the prediction. Maybe it's a simple Virtualbox/NAT configuration that I'm not managing well

**Comment by mingfang** [comment]
Just to be clear, is your setup desktop -> virtual box -> docker (PredictionIO)?
If so then you will have to setup port forwarding on virtual box.

**Comment by rodolfobandeira** [comment]
Hi @mingfang ! 
I was looking for some info about port-forwarding on boot2docker and found @SvenDowideit 's answer [here](https://github.com/docker/docker/issues/4007#issuecomment-60538551)

So, I followed the instruction steps and it's working now!
```
boot2docker up
eval "$(boot2docker shellinit)"
docker run --name predictionio -d -p 9000:9000 predictionio
open http://$(boot2docker ip 2>/dev/null):9000/
```
Maybe this could be useful in your readme! 
Thank you!

**Comment by mingfang** [comment]
Thanks for the update.
