### ISSUE TITLE
Error : E: Unable to locate package runit

### ISSUE THREAD

**Issue by ibutcha** [mingfang/docker-predictionio#17]
Hi,

I am having issue running the docker file, I keep getting the error:

E: Unable to locate package runit

Was wondering what I could do to get it working.

Logs:

Step 0 : FROM ubuntu:14.04
 ---> 91e54dfb1179
Step 1 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> c36c6481d2a9
Step 2 : RUN apt-get update
 ---> Using cache
 ---> 50b95f08bbe9
Step 3 : RUN locale-gen en_US en_US.UTF-8
 ---> Using cache
 ---> e51f046a4c87
Step 4 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 9c801c5b16cf
Step 5 : RUN echo "export PS1='\e[1;31m]\u@\h:\w\$[\e[0m] '" >> /root/.bashrc
 ---> Using cache
 ---> b64bf5366406
Step 6 : RUN apt-get install -y runit
 ---> Running in fb552ed1da32
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package runit

**Comment by mingfang** [comment]
The base image may need to get updated.
Try doing ```docker pull ubuntu:14.04``` and then build again.

**Comment by ibutcha** [comment]
charlie@charlie:~/Desktop/PridictionIO/docker-predictionio$ sudo docker pull ubuntu:14.04
[sudo] password for charlie: 
14.04: Pulling from library/ubuntu

0a85502c06c9: Pull complete 
0998bf8fb9e9: Pull complete 
a6785352b25c: Pull complete 
e9ae3c220b23: Pull complete 
Digest: sha256:28bd2edcebe82d41c3494bf6205016fe08e681452f1448acd44d55e2cda7e3c0
Status: Downloaded newer image for ubuntu:14.04


charlie@charlie:~/Desktop/PridictionIO/docker-predictionio$ sudo ./build
Sending build context to Docker daemon 113.2 kB
Step 1 : FROM ubuntu:14.04
 ---> e9ae3c220b23
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 420dc9b0b0dc
Step 3 : RUN apt-get update
 ---> Using cache
 ---> c617bb2e64ae
Step 4 : RUN locale-gen en_US en_US.UTF-8
 ---> Using cache
 ---> fb738c1657b0
Step 5 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> f2334f03d708
Step 6 : RUN echo "export PS1='\e[1;31m\]\u@\h:\w\\$\[\e[0m\] '" >> /root/.bashrc
 ---> Using cache
 ---> 52e5d565fe92
Step 7 : RUN apt-get install -y runit
 ---> Running in 0a9d1b94e156
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package runit

I got the same error after I build the ubuntu:14.04..

**Comment by mingfang** [comment]
The problem is the apt repo changed. 
Besides pulling the new ubuntu image, also build without cache.
Try ```./build --no-cache```

**Comment by ibutcha** [comment]
charlie@charlie:~/Desktop/PridictionIO/docker-predictionio$ sudo  ./build --no-cache
Sending build context to Docker daemon 113.2 kB
Step 1 : FROM ubuntu:14.04
 ---> e9ae3c220b23
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in a5085d42c768
 ---> e2f0c923679c
Removing intermediate container a5085d42c768
Step 3 : RUN apt-get update
 ---> Running in 35a8defc8924
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
 ---> 1efc089f6f7d
Removing intermediate container 35a8defc8924
Step 4 : RUN locale-gen en_US en_US.UTF-8
 ---> Running in c920a9a306da
Generating locales...
  en_US.ISO-8859-1... done
  en_US.UTF-8... done
Generation complete.
 ---> c13ba7b62989
Removing intermediate container c920a9a306da
Step 5 : ENV LANG en_US.UTF-8
 ---> Running in a66896bccee2
 ---> 0e5d7485dc91
Removing intermediate container a66896bccee2
Step 6 : RUN echo "export PS1='\e[1;31m\]\u@\h:\w\\$\[\e[0m\] '" >> /root/.bashrc
 ---> Running in 2060fdfef77e
 ---> 649b1b741394
Removing intermediate container 2060fdfef77e
Step 7 : RUN apt-get install -y runit
 ---> Running in cedb51105820
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package runit

**Comment by mingfang** [comment]
I upgraded to ubuntu:16.04.
Can you pull the latest and try again?

**Comment by feizeikesi** [comment]
@mingfang Error is still

**Comment by mingfang** [comment]
I made several improvements.
Please try again.

**Comment by mingfang** [comment]
assume fixed
