### ISSUE TITLE
Error opening the dashboard

### ISSUE THREAD

**Issue by rafaelcvr** [mingfang/docker-predictionio#22]
I'm getting the following error when accessing the dashboard at port 9000:

> The supplied authentication is invalid

**Comment by nlauchande** [comment]
I am also having the same error.

**Comment by wlzch** [comment]
Me too. Any solution?

**Comment by neoty** [comment]
Me too..

**Comment by mingfang** [comment]
sorry I've been busy.
I'll fix it tomorrow.

**Comment by marcusvas** [comment]
when i try https://localhost:9000 i got this message in browser: "the supplied authentication is invalid".

**Comment by KennyTw** [comment]
Hi ! @marcusvas  , according to this doc page http://predictionio.incubator.apache.org/evaluation/evaluationdashboard/ 
https://localhost:9000/?accessKey=  
works for me .

**Comment by mingfang** [comment]
I upgraded to newer version and am no longer seeing the error.
Please try again.
