### ISSUE TITLE
Facing issue with sbt installation

### ISSUE THREAD

**Issue by naveenkumarmarri** [mingfang/docker-predictionio#24]
Hi,

I'm trying to install predictionIO using docker image,I'm facing issue when 

`RUN /PredictionIO/sbt/sbt package`

code is invoked. It is throwing server access error:Connection refused.

**Comment by mingfang** [comment]
can you please paste the full log here?

**Comment by naveenkumarmarri** [comment]
`:: problems summary ::
:::: WARNINGS
	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.7/ivys/ivy.xml: Connection refused (Connection refused) (80460ms)

		module not found: org.scala-sbt#logging;0.13.7

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/logging/0.13.7/ivys/ivy.xml

	  -- artifact org.scala-sbt#logging;0.13.7!logging.jar:

	  /root/.ivy2/local/org.scala-sbt/logging/0.13.7/jars/logging.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.7/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/logging/0.13.7/logging-0.13.7.pom

	  -- artifact org.scala-sbt#logging;0.13.7!logging.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/logging/0.13.7/logging-0.13.7.jar

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml: Connection refused (Connection refused) (81404ms)

		module not found: org.scala-tools.sbinary#sbinary_2.10;0.4.2

	==== local: tried

	  /root/.ivy2/local/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml

	  -- artifact org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar:

	  /root/.ivy2/local/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-tools/sbinary/sbinary_2.10/0.4.2/sbinary_2.10-0.4.2.pom

	  -- artifact org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar:

	  https://repo1.maven.org/maven2/org/scala-tools/sbinary/sbinary_2.10/0.4.2/sbinary_2.10-0.4.2.jar

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.7/ivys/ivy.xml: Connection refused (Connection refused) (75250ms)

		module not found: org.scala-sbt#run;0.13.7

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/run/0.13.7/ivys/ivy.xml

	  -- artifact org.scala-sbt#run;0.13.7!run.jar:

	  /root/.ivy2/local/org.scala-sbt/run/0.13.7/jars/run.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.7/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/run/0.13.7/run-0.13.7.pom

	  -- artifact org.scala-sbt#run;0.13.7!run.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/run/0.13.7/run-0.13.7.jar

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.7/ivys/ivy.xml: Connection refused (Connection refused) (75575ms)

		module not found: org.scala-sbt#apply-macro;0.13.7

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/apply-macro/0.13.7/ivys/ivy.xml

	  -- artifact org.scala-sbt#apply-macro;0.13.7!apply-macro.jar:

	  /root/.ivy2/local/org.scala-sbt/apply-macro/0.13.7/jars/apply-macro.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.7/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/apply-macro/0.13.7/apply-macro-0.13.7.pom

	  -- artifact org.scala-sbt#apply-macro;0.13.7!apply-macro.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/apply-macro/0.13.7/apply-macro-0.13.7.jar

		[FAILED     ] org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar: Connection refused (Connection refused) (91649ms)

		[FAILED     ] org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar: Connection refused (Connection refused) (91649ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_2/0.13.7/jars/compiler-interface-bin.jar

		[NOT FOUND  ] org.scala-sbt#actions;0.13.7!actions.jar (83334ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.7/jars/actions.jar

		[FAILED     ] org.scala-sbt#main-settings;0.13.7!main-settings.jar: Connection refused (Connection refused) (90886ms)

		[FAILED     ] org.scala-sbt#main-settings;0.13.7!main-settings.jar: Connection refused (Connection refused) (90886ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.7/jars/main-settings.jar

		[NOT FOUND  ] org.scala-sbt#control;0.13.7!control.jar (75418ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.7/jars/control.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#logging;0.13.7: not found

		:: org.scala-tools.sbinary#sbinary_2.10;0.4.2: not found

		:: org.scala-sbt#run;0.13.7: not found

		:: org.scala-sbt#apply-macro;0.13.7: not found

		::::::::::::::::::::::::::::::::::::::::::::::


		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#actions;0.13.7!actions.jar

		:: org.scala-sbt#control;0.13.7!control.jar

		:: org.scala-sbt#main-settings;0.13.7!main-settings.jar

		:: org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/launcher-interface/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/com.jcraft/jsch/0.1.46/ivys/ivy.xml

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.7/jars/main.jar.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_3/0.13.7/jars/compiler-interface-bin.jar.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_3/0.13.7/jars/compiler-interface-bin.jar.md5

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.7/jars/actions.jar

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.7/jars/control.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#logging;0.13.7: not found
unresolved dependency: org.scala-tools.sbinary#sbinary_2.10;0.4.2: not found
unresolved dependency: org.scala-sbt#run;0.13.7: not found
unresolved dependency: org.scala-sbt#apply-macro;0.13.7: not found
download failed: org.scala-sbt#actions;0.13.7!actions.jar
download failed: org.scala-sbt#control;0.13.7!control.jar
download failed: org.scala-sbt#main-settings;0.13.7!main-settings.jar
download failed: org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.7
The command '/bin/sh -c /PredictionIO/sbt/sbt package' returned a non-zero code: 1
`

**Comment by mingfang** [comment]
My guess is that there was a momentary problem with the public maven repo.
I just tried it and am not seeing this error.
Can you try again now?

**Comment by naveenkumarmarri** [comment]
I guess there is 302 response

`:: problems summary ::
:::: WARNINGS
	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.7/ivys/ivy.xml: Connection refused (Connection refused) (80460ms)

		module not found: org.scala-sbt#logging;0.13.7

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/logging/0.13.7/ivys/ivy.xml

	  -- artifact org.scala-sbt#logging;0.13.7!logging.jar:

	  /root/.ivy2/local/org.scala-sbt/logging/0.13.7/jars/logging.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.7/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/logging/0.13.7/logging-0.13.7.pom

	  -- artifact org.scala-sbt#logging;0.13.7!logging.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/logging/0.13.7/logging-0.13.7.jar

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml: Connection refused (Connection refused) (81404ms)

		module not found: org.scala-tools.sbinary#sbinary_2.10;0.4.2

	==== local: tried

	  /root/.ivy2/local/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml

	  -- artifact org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar:

	  /root/.ivy2/local/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-tools/sbinary/sbinary_2.10/0.4.2/sbinary_2.10-0.4.2.pom

	  -- artifact org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar:

	  https://repo1.maven.org/maven2/org/scala-tools/sbinary/sbinary_2.10/0.4.2/sbinary_2.10-0.4.2.jar

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.7/ivys/ivy.xml: Connection refused (Connection refused) (75250ms)

		module not found: org.scala-sbt#run;0.13.7

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/run/0.13.7/ivys/ivy.xml

	  -- artifact org.scala-sbt#run;0.13.7!run.jar:

	  /root/.ivy2/local/org.scala-sbt/run/0.13.7/jars/run.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.7/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/run/0.13.7/run-0.13.7.pom

	  -- artifact org.scala-sbt#run;0.13.7!run.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/run/0.13.7/run-0.13.7.jar

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.7/ivys/ivy.xml: Connection refused (Connection refused) (75575ms)

		module not found: org.scala-sbt#apply-macro;0.13.7

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/apply-macro/0.13.7/ivys/ivy.xml

	  -- artifact org.scala-sbt#apply-macro;0.13.7!apply-macro.jar:

	  /root/.ivy2/local/org.scala-sbt/apply-macro/0.13.7/jars/apply-macro.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.7/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/apply-macro/0.13.7/apply-macro-0.13.7.pom

	  -- artifact org.scala-sbt#apply-macro;0.13.7!apply-macro.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/apply-macro/0.13.7/apply-macro-0.13.7.jar

		[FAILED     ] org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar: Connection refused (Connection refused) (91649ms)

		[FAILED     ] org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar: Connection refused (Connection refused) (91649ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_2/0.13.7/jars/compiler-interface-bin.jar

		[NOT FOUND  ] org.scala-sbt#actions;0.13.7!actions.jar (83334ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.7/jars/actions.jar

		[FAILED     ] org.scala-sbt#main-settings;0.13.7!main-settings.jar: Connection refused (Connection refused) (90886ms)

		[FAILED     ] org.scala-sbt#main-settings;0.13.7!main-settings.jar: Connection refused (Connection refused) (90886ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.7/jars/main-settings.jar

		[NOT FOUND  ] org.scala-sbt#control;0.13.7!control.jar (75418ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.7/jars/control.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#logging;0.13.7: not found

		:: org.scala-tools.sbinary#sbinary_2.10;0.4.2: not found

		:: org.scala-sbt#run;0.13.7: not found

		:: org.scala-sbt#apply-macro;0.13.7: not found

		::::::::::::::::::::::::::::::::::::::::::::::


		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#actions;0.13.7!actions.jar

		:: org.scala-sbt#control;0.13.7!control.jar

		:: org.scala-sbt#main-settings;0.13.7!main-settings.jar

		:: org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/launcher-interface/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/com.jcraft/jsch/0.1.46/ivys/ivy.xml

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.7/jars/main.jar.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_3/0.13.7/jars/compiler-interface-bin.jar.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_3/0.13.7/jars/compiler-interface-bin.jar.md5

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.7/jars/actions.jar

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.7/jars/control.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#logging;0.13.7: not found
unresolved dependency: org.scala-tools.sbinary#sbinary_2.10;0.4.2: not found
unresolved dependency: org.scala-sbt#run;0.13.7: not found
unresolved dependency: org.scala-sbt#apply-macro;0.13.7: not found
download failed: org.scala-sbt#actions;0.13.7!actions.jar
download failed: org.scala-sbt#control;0.13.7!control.jar
download failed: org.scala-sbt#main-settings;0.13.7!main-settings.jar
download failed: org.scala-sbt#precompiled-2_9_2;0.13.7!compiler-interface-bin.jar
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.7
The command '/bin/sh -c /PredictionIO/sbt/sbt package' returned a non-zero code: 1
`

**Comment by naveenkumarmarri** [comment]
looks like there is 302 response. Does this have to do something with the error?


`Step 27/44 : RUN /PredictionIO/sbt/sbt package
 ---> Running in c6669ed18137
Attempting to fetch sbt
*   Trying 52.203.61.63...
* Connected to repo.typesafe.com (52.203.61.63) port 80 (#0)
> GET /typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar HTTP/1.1
> Host: repo.typesafe.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html
< Date: Mon, 03 Apr 2017 18:50:07 GMT
< Location: http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar
< Server: nginx/1.8.0
< Content-Length: 160
< Connection: keep-alive
< 
* Ignoring the response-body
{ [160 bytes data]
######################################################################## 100.0%* Connection #0 to host repo.typesafe.com left intact
* Issue another request to this URL: 'http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar'
*   Trying 54.148.163.235...
* Connected to dl.bintray.com (54.148.163.235) port 80 (#1)
> GET /typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar HTTP/1.1
> Host: dl.bintray.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 
< Server: nginx
< Date: Mon, 03 Apr 2017 18:58:10 GMT
< Content-Length: 0
< Location: http://akamai.bintray.com/b4/b407b2a76ad72165f806ac7e7ea09132b951ef53?__gda__=exp=1491246610~hmac=af941b1c23ed09453b140011c65bab461703bdf6efe448a55dabecc214f45fb8&response-content-disposition=attachment%3Bfilename%3D%22sbt-launch.jar%22&response-content-type=application%2Foctet-stream&requestInfo=U2FsdGVkX1-q7bCqqoBZr3jn1WDYrV8u_s9QdFLexH0MsS4ye8rp21k1okdigk3L1xZszBhkLrrvM5rRDw_dH16vHCmXM770VsxLgtOpBLysLBmF2NmELejIHU3e3n_hYeo3-CE0wvbnrz2Hbm5IufIouL95UeMAjGZ3tRdiP40
< Connection: keep-alive
< 
* Connection #1 to host dl.bintray.com left intact
* Issue another request to this URL: 'http://akamai.bintray.com/b4/b407b2a76ad72165f806ac7e7ea09132b951ef53?__gda__=exp=1491246610~hmac=af941b1c23ed09453b140011c65bab461703bdf6efe448a55dabecc214f45fb8&response-content-disposition=attachment%3Bfilename%3D%22sbt-launch.jar%22&response-content-type=application%2Foctet-stream&requestInfo=U2FsdGVkX1-q7bCqqoBZr3jn1WDYrV8u_s9QdFLexH0MsS4ye8rp21k1okdigk3L1xZszBhkLrrvM5rRDw_dH16vHCmXM770VsxLgtOpBLysLBmF2NmELejIHU3e3n_hYeo3-CE0wvbnrz2Hbm5IufIouL95UeMAjGZ3tRdiP40'
*   Trying 23.35.7.16...
* Connected to akamai.bintray.com (23.35.7.16) port 80 (#2)
> GET /b4/b407b2a76ad72165f806ac7e7ea09132b951ef53?__gda__=exp=1491246610~hmac=af941b1c23ed09453b140011c65bab461703bdf6efe448a55dabecc214f45fb8&response-content-disposition=attachment%3Bfilename%3D%22sbt-launch.jar%22&response-content-type=application%2Foctet-stream&requestInfo=U2FsdGVkX1-q7bCqqoBZr3jn1WDYrV8u_s9QdFLexH0MsS4ye8rp21k1okdigk3L1xZszBhkLrrvM5rRDw_dH16vHCmXM770VsxLgtOpBLysLBmF2NmELejIHU3e3n_hYeo3-CE0wvbnrz2Hbm5IufIouL95UeMAjGZ3tRdiP40 HTTP/1.1
> Host: akamai.bintray.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache
< ETag: "7341059aa30c953021d6af41c89d2cac:1454730505"
< Last-Modified: Tue, 21 Apr 2015 16:03:07 GMT
< Accept-Ranges: bytes
< Content-Length: 1208380
< Date: Mon, 03 Apr 2017 18:58:11 GMT
< Content-Type: application/octet-stream
< content-disposition: attachment;filename="sbt-launch.jar"
< Connection: keep-alive
< 
{ [1107 bytes data]
######################################################################## 100.0%* Connection #2 to host akamai.bintray.com left intact`

**Comment by mingfang** [comment]
The 302 is normal and should not cause any errors.

How you still seeing errors?...Your new log did not show any.

**Comment by naveenkumarmarri** [comment]
That is before the execution of 

Launching sbt from /PredictionIO/sbt/sbt-launch-0.13.7.jar
Getting org.scala-sbt sbt 0.13.7 ...

I triggered the docker build, it is in progress

**Comment by naveenkumarmarri** [comment]
Still facing the same issue.

`
:: problems summary ::
:::: WARNINGS
		[FAILED     ] org.scala-sbt#compiler-interface;0.13.7!compiler-interface-bin.jar: Connection refused (Connection refused) (82240ms)

		[FAILED     ] org.scala-sbt#compiler-interface;0.13.7!compiler-interface-bin.jar: Connection refused (Connection refused) (82240ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.7/jars/compiler-interface-bin.jar

		[NOT FOUND  ] org.scala-sbt#incremental-compiler;0.13.7!incremental-compiler.jar (77344ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.7/jars/incremental-compiler.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#incremental-compiler;0.13.7!incremental-compiler.jar

		:: org.scala-sbt#compiler-interface;0.13.7!compiler-interface-bin.jar

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.7/ivys/ivy.xml.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.7/jars/run.jar.sha1

	Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.7/jars/incremental-compiler.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: org.scala-sbt#incremental-compiler;0.13.7!incremental-compiler.jar
download failed: org.scala-sbt#compiler-interface;0.13.7!compiler-interface-bin.jar
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.7
The command '/bin/sh -c /PredictionIO/sbt/sbt package' returned a non-zero code: 1`

**Comment by mingfang** [comment]
I removed that line and upgraded to newer version.
Please try again.

**Comment by MichalGallovic** [comment]
Hey, just chimming in ... I installed the image and did not face any issues. So the problem was resolved 👍

**Comment by mingfang** [comment]
@MichalGallovic thanks for the confirmation.

**Comment by jobsfan** [comment]
> I removed that line and upgraded to newer version. Please try again.

http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.15/sbt-launch.jar

**Comment by jobsfan** [comment]
> I removed that line and upgraded to newer version. Please try again.

http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.15/sbt-launch.jar
this link is not reachable. 

I am trying to build the image according to the installation guide, but failed
