### ISSUE TITLE
Invalid Template Error

### ISSUE THREAD

**Issue by erayalakese** [mingfang/docker-predictionio#25]
When I execute `./run.sh` file inside quickstartapp directory, I'm getting this error:

```[ERROR] [Template$] This engine template requires at least PredictionIO 0.10.0-incubating. The template may not work with PredictionIO 0.9.6.```

**Comment by mingfang** [comment]
I upgraded to PredictionIO v0.10.0-incubating.
Please pull and rebuild the image to try again.

**Comment by mingfang** [comment]
try the latest version.
reopen if same problem
