### ISSUE TITLE
Java Out of Memory when Running

### ISSUE THREAD

**Issue by rakshitcr7** [mingfang/docker-predictionio#26]
I have followed all the steps in the README. Now when I run the "./run.sh" command from the quickstartapp directory, the insufficient memory error occurs. This happens after the console outputs "Your Engine is Ready for Training".
Following is the error which occurs:
 `Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000715550000, 2863333376, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2863333376 bytes for committing reserved memory.
`

I have also tried icreasing the Java Heap Size using "export _JAVA_OPTIONS=-Xmx1024m" but no use.

**Comment by mingfang** [comment]
The training step requires 4GB of RAM.
You may try a smaller number here https://github.com/mingfang/docker-predictionio/blob/master/quickstartapp/run.sh#L51

**Comment by rakshitcr7** [comment]
I have increased my RAM and now the ./run.sh command runs successfully. However when I change my directory to MyRecommendation and try to deploy my engine, I get the following error:

>  [ERROR] [Console$] No valid engine instance found for engine t8yaJDyWta5bNwTVs6wVZ1I8BhnoHUVH d226d35564d904d3c6610458191c461c1b2fc9ff.
> Try running 'train' before 'deploy'. Aborting.

I have one more query whether the RAM needed would be less if I used a smaller input data?

**Comment by mingfang** [comment]
try the latest version.
please reopen if you're still see this problem.
