### ISSUE TITLE
Containers share prediction apps

### ISSUE THREAD

**Issue by szyszka90** [mingfang/docker-predictionio#30]
When I run two containers on the same host, the second container after run `runsvdir-start&` and `pio app list` shows app which has been created in the first container. I was sure that containers are independent. I don't know if there is a problem in this specific Dockerfile or this is how Docker just works (?). I've noticed that after run `runsvdir-start&` on the fresh container, elasticsearch contains exactly the same data as elasticsearch in the first container so I suppose that elasticsearch layer  is common for both containers (and maybe other services (?)).

I've made a test with simple redis container and there are not shared keys between containers so I think that sharing data between containers is specific for Dockerfile from this repo. 

How can I run independent containers?

**Comment by mingfang** [comment]
This sounds like something is really wrong.
Please email me so that I can help you.
