### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by fethisen** [mingfang/docker-predictionio#32]
When I was trying to build i got this error. I am using ubuntu 16:04. 

`build: 2: build: source: not found
invalid argument "." for t: Error parsing reference: "." is not a valid repository/tag: invalid reference format
See 'docker build --help'.`

**Comment by mingfang** [comment]
what version of docker are you using?

**Comment by fethisen** [comment]
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
```

**Comment by mingfang** [comment]
This requires a newer version of Docker that has the multi-stage build features.
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by fethisen** [comment]
thanks for your interest
