### ISSUE TITLE
 Unable to connect to all storage backends successfully.

### ISSUE THREAD

**Issue by JackyW83** [mingfang/docker-predictionio#37]
Hi guys,

Can anybody assist this error?
I ran `runsvdir-start&` inside container, then ran `pio status` and got below message:

> [ERROR] [Management$] Unable to connect to all storage backends successfully.
> The following shows the error message from the storage backend.
> 
> Only 0 of 1 regions are online; retries exhausted. (org.apache.hadoop.hbase.client.RegionOfflineException)
> 
> Dumping configuration of initialized storage backend sources.
> Please make sure they are correct.
> 

thanks

**Comment by donedgardo** [comment]
I'm having this same situation.

**Comment by mingfang** [comment]
Sometimes this happens when your’e system does not have enough memory.
How much memory do you have?

**Comment by donedgardo** [comment]
I think your right @mingfang how much memory is recommended?

**Comment by mingfang** [comment]
I recommend at least 5GB RAM

**Comment by JackyW83** [comment]
my machine has 16gb memory. anyway, I changed to another docker image, and it's working fine for me, close this issue
